[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "noshow-iq-11939-hidayat-final"  # Change this to be unique
version = "0.1.0"
authors = [
  { name="HidayatUllah", email="hidayatkarim43@gmail.com" },
]
description = "A prediction API for medical appointment no-shows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "scikit-learn",
    "fastapi",
    "uvicorn",
    "pymongo",
    "joblib"
]

[project.urls]
"Homepage" = "https://github.com/Hedayatullah999/noshow-iq--11939-"

[tool.setuptools]
packages = ["noshow_iq"]